// This file is auto-generated by TanStack Start during build/dev.
// Placeholder for typecheck — will be replaced by the build.
import { createRootRoute, createFileRoute } from '@tanstack/react-router'

const rootRoute = createRootRoute()
const indexRoute = createFileRoute('/')({})

export const routeTree = rootRoute.addChildren([indexRoute])
